import type { KnowledgeItem } from "@prisma/client";

/**
 * What the studio teaches, who each program suits and where it leads. Seeded once so the agent
 * has something true to sell from on day one; staff edit these in /coach/leads/knowledge.
 *
 * Anything with a price or a class time is seeded `verified: false` — the agent refuses to quote
 * unverified facts, so a placeholder can never be texted to a lead as if it were real.
 */
export const SEED_KNOWLEDGE: Array<
  Pick<KnowledgeItem, "category" | "title" | "body" | "audience" | "program" | "order" | "verified">
> = [
  {
    category: "PROGRAM",
    title: "Muay Thai — adults",
    body: "Thai kickboxing: punches, kicks, elbows, knees and clinch work. Classes start with pad rounds, so beginners get a workout from day one without sparring. Best fit for adults who want conditioning plus striking skill. No experience needed; gloves and wraps can be borrowed for the first few classes.",
    audience: "ADULTS",
    program: "Muay Thai",
    order: 10,
    verified: true,
  },
  {
    category: "PROGRAM",
    title: "BJJ — adults",
    body: "Brazilian Jiu-Jitsu: grappling and ground control — takedowns, positions, escapes and submissions. Adults train no-gi on weeknights (rash guard and shorts) and gi on Saturday mornings; loaner gis are available. Lower impact than striking. Best fit for adults who want self defense, problem-solving and a training community. Beginners drill technique with partners and never spar on day one.",
    audience: "ADULTS",
    program: "Brazilian Jiu-Jitsu",
    order: 11,
    verified: true,
  },
  {
    category: "PROGRAM",
    title: "Judo — kids",
    body: "Olympic throwing art: grip fighting, throws, breakfalls and pins. Kids learn to fall safely, which carries over to every other sport, and it pairs well with the grappling in our other kids classes.",
    audience: "KIDS",
    program: "Judo",
    order: 12,
    verified: true,
  },
  {
    category: "PROGRAM",
    title: "Cardio Kickboxing — adults",
    body: "Striking-based conditioning class: pads, bags and rounds, no sparring. Best fit for an adult whose first goal is fitness rather than fighting, and an easy first class for someone nervous about contact.",
    audience: "ADULTS",
    program: "Cardio Kickboxing",
    order: 13,
    verified: true,
  },
  {
    category: "PROGRAM",
    title: "Kids classes and levels",
    body: "Kids train by level, not age alone: Curious Cubs for ages 4-6, then Fundamentals, then Advanced as they progress, plus Kids Judo and Kids Muay Thai. Coaches run structured games and technique drills; no hard sparring. Parents watch from the mat side. Common reasons parents enrol: confidence, bullying, burning energy, and an activity that is not a team sport.",
    audience: "KIDS",
    program: "",
    order: 14,
    verified: true,
  },
  {
    category: "PROGRAM",
    title: "Muay Thai Sparring — adults",
    body: "Supervised sparring for members who already train striking and want live rounds. Never a beginner's first class: send a new adult to Muay Thai or Cardio Kickboxing instead.",
    audience: "ADULTS",
    program: "Muay Thai",
    order: 15,
    verified: true,
  },
  {
    category: "PROGRAM",
    title: "Private sessions",
    body: "One-to-one coaching, available Wednesday evening and Saturday midday. Best for someone preparing for a grading or competition, coming back from time off, or who wants to catch up on what a class covered. Frame it as accelerating, not as remedial. A coach quotes private rates, not the agent.",
    audience: "ALL",
    program: "Private Training",
    order: 16,
    verified: true,
  },
  {
    category: "POLICY",
    title: "First class is free",
    body: "Every prospective student gets a free trial class in the program that fits them. They should arrive 10 minutes early, wear shorts and a t-shirt, and bring water. Loaner gear is available. No contract is signed to try a class.",
    audience: "ALL",
    program: "",
    order: 20,
    verified: true,
  },
  {
    category: "POLICY",
    title: "Location and contact",
    body: "Atheneum Martial Arts, 825 Meander Court, Medina, MN 55340. Phone (763) 342-5614.",
    audience: "ALL",
    program: "",
    order: 21,
    verified: true,
  },
  {
    category: "PRICING",
    title: "Adult membership rates",
    body: "Adults: $175 per month unlimited across every program, or $160 per month for a single program. Quote these as the standard rates. Anything below them is a conversation for a coach, not for text.",
    audience: "ADULTS",
    program: "",
    order: 30,
    verified: true,
  },
  {
    category: "PRICING",
    title: "Kids membership rates",
    body: "Kids pricing depends on how often the child trains — one class a week, two, or unlimited — and the tiers came out of specific conversations with specific families rather than a published price list. The agent never quotes a kids rate over text: ask how many days a week they are picturing, then hand off so a coach can price it. The first class is free regardless.",
    audience: "KIDS",
    program: "",
    order: 31,
    verified: true,
  },
  {
    category: "PRICING",
    title: "How to talk about price",
    body: "Rates move with what a family needs, so quote the standard rate as a starting point and never promise a discount, a family rate, a promotion or a custom package — a coach agrees those in person. If they push for a deal, hand off. The first class is free regardless of what they end up paying.",
    audience: "ALL",
    program: "",
    order: 32,
    verified: true,
  },
  {
    category: "SCHEDULE",
    title: "Weekly class schedule (as of 08/01/2026)",
    body: [
      "Monday: 5:15pm Kids Gi BJJ (Fundamentals), 6:15pm Muay Thai, 7:15pm No Gi BJJ.",
      "Tuesday: 4:15pm Kids No Gi BJJ (Fundamentals), 5:15pm Kids No Gi BJJ (Advanced), 6:15pm No Gi BJJ.",
      "Wednesday: 5:15pm Kids Judo (all ages, gi), 6:15pm Judo, 7:15pm private sessions.",
      "Thursday: 6:15pm Kids Muay Thai (Fundamentals), 7:15pm Cardio Kickboxing.",
      "Friday: 5:15pm Kids No Gi BJJ (Fundamentals), 6:15pm Muay Thai, 7:15pm Muay Thai Sparring.",
      "Saturday: 11am Gi BJJ, 12pm private sessions.",
      "Sunday: 2:15pm Curious Cubs No Gi BJJ (ages 4-6), 3pm Kids Gi BJJ (Fundamentals), 4pm Kids No Gi BJJ (Advanced).",
      "Offer a class from the upcoming list the system gives you, since it accounts for cancellations. If that list is empty, do not name a day or time from this item — hand off so a coach can confirm.",
    ].join(" "),
    audience: "ALL",
    program: "",
    order: 33,
    verified: true,
  },
  {
    category: "OBJECTION",
    title: "\"How much is it?\" early in the conversation",
    body: "Answer the question honestly, do not dodge it, but anchor it to the free trial: give the rate if it is verified, then offer a class time. Never quote a range you are guessing at.",
    audience: "ALL",
    program: "",
    order: 40,
    verified: true,
  },
  {
    category: "OBJECTION",
    title: "\"I'm not in shape yet\"",
    body: "The most common objection, and it is really fear of embarrassment. Reassure that beginners start in the beginner class, everyone was new once, and conditioning comes from training rather than before it. Offer a specific quiet class time.",
    audience: "ADULTS",
    program: "",
    order: 41,
    verified: true,
  },
  {
    category: "OBJECTION",
    title: "\"I'm worried my child will get hurt\"",
    body: "Kids classes have no hard sparring; drilling is supervised and age-grouped, and breakfalls are taught before throws. Invite the parent to watch a class from the side before deciding.",
    audience: "KIDS",
    program: "",
    order: 42,
    verified: true,
  },
  {
    category: "OBJECTION",
    title: "\"I don't have time\"",
    body: "Ask which days would realistically work rather than arguing. Two classes a week is enough to progress. If the schedule genuinely does not fit, say so and offer to follow up when the next term starts.",
    audience: "ALL",
    program: "",
    order: 43,
    verified: true,
  },
  {
    category: "UPSELL",
    title: "Second discipline",
    body: "Once a student is training consistently, the natural add-on is a complementary art: BJJ students add Judo for takedowns, Muay Thai students add BJJ for the ground, either adds MMA. Offer it after a milestone, never in the first month.",
    audience: "ALL",
    program: "",
    order: 50,
    verified: true,
  },
  {
    category: "UPSELL",
    title: "Family add-on",
    body: "Parents who watch their child train every week are the warmest lead in the building. Ask if they have ever wanted to try it themselves, and offer them the same free trial.",
    audience: "ALL",
    program: "",
    order: 51,
    verified: true,
  },
  {
    category: "UPSELL",
    title: "Private lessons",
    body: "Best offered to students preparing for a grading or competition, or ones who miss group classes often. Frame as accelerating what they are already doing, not as a fix for being behind.",
    audience: "ALL",
    program: "",
    order: 52,
    verified: true,
  },
  {
    category: "UPSELL",
    title: "Referrals",
    body: "Training partners keep people enrolled. Ask happy students who they train with outside the gym, and offer their friend the same free trial. Best asked after a milestone or a competition.",
    audience: "ALL",
    program: "",
    order: 53,
    verified: true,
  },
];
